IF DB_ID ('nicarWashs') IS NOT NULL
BEGIN USE MASTER DROP DATABASE nicarWashs END

/* luego la secuencia sigue y creamos la base de datos */

CREATE DATABASE nicarWashs
GO

--Usamos la base de datos creada
USE nicarWashs
GO

--------------------------------------EMPLEADOS-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------V------------------------------------------------------------------------------------------------------------------------------------------------------
-- CREANDO TABLA EMPLEADO
CREATE TABLE EMPLEADOS(
ID_EMPLEADO INT IDENTITY(2001,1) PRIMARY KEY NOT NULL,
CODIGO_EMPLEADO VARCHAR(10) CHECK(CODIGO_EMPLEADO LIKE '[A-Z][A-Z]-[0-9][0-9][0-9][0-9]-[0-9][0-9]') NOT NULL,
PRIMER_NOMBRE VARCHAR(50) NOT NULL,
PRIMER_APELLIDO VARCHAR(50) NOT NULL,
TELEFONO CHAR (8) CHECK (TELEFONO like '[5|7|8][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
SEGUNDO_NOMBRE VARCHAR(50),
SEGUNDO_APELLIDO VARCHAR(50),
CORREO VARCHAR(50),
CEDULA VARCHAR (16) constraint ck_cedula_pattern  CHECK (CEDULA LIKE '[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][A-Z]') NOT NULL,
TIPO_EMPLEADO VARCHAR (50) CHECK (TIPO_EMPLEADO = 'Administracion' OR TIPO_EMPLEADO = 'Mecanica'OR TIPO_EMPLEADO = 'Limpieza'OR TIPO_EMPLEADO = 'Seguridad') NOT NULL,
DIRECCION VARCHAR(MAX) NOT NULL,
TELEFONO_EMERGENCIA CHAR(8) CHECK ( TELEFONO_EMERGENCIA LIKE '[5|7|8][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
PARENTESCO VARCHAR(50) NOT NULL,
ESTADO BIT DEFAULT 1
)
GO

-- CREANDO TABLA TEMPORAL DE EMPLEADOS
CREATE TABLE TEMPOEMPLEADOS(
ID_EMPLEADO INT IDENTITY(2001,1) PRIMARY KEY NOT NULL,
CODIGO_EMPLEADO VARCHAR(10) CHECK(CODIGO_EMPLEADO LIKE '[A-Z][A-Z]-[0-9][0-9][0-9][0-9]-[0-9][0-9]') NOT NULL,
PRIMER_NOMBRE VARCHAR(50) NOT NULL,
PRIMER_APELLIDO VARCHAR(50) NOT NULL,
TELEFONO CHAR (8) CHECK (TELEFONO like '[5|7|8][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
SEGUNDO_NOMBRE VARCHAR(50),
SEGUNDO_APELLIDO VARCHAR(50),
CORREO VARCHAR(50),
CEDULA VARCHAR (16) constraint cedula_pattern  CHECK (CEDULA LIKE '[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][A-Z]') NOT NULL,
TIPO_EMPLEADO VARCHAR (50) CHECK (TIPO_EMPLEADO = 'Administracion' OR TIPO_EMPLEADO = 'Mecanica'OR TIPO_EMPLEADO = 'Limpieza'OR TIPO_EMPLEADO = 'Seguridad') NOT NULL,
DIRECCION VARCHAR(MAX) NOT NULL,
TELEFONO_EMERGENCIA CHAR(8) CHECK ( TELEFONO_EMERGENCIA LIKE '[5|7|8][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
PARENTESCO VARCHAR(50) NOT NULL,
ESTADO BIT DEFAULT 0
)
GO


--TRIGGER DE ESTADO DE EMPLEADO
CREATE  TRIGGER ESTADOEMPLEADO
ON EMPLEADOS
 AFTER UPDATE AS 

 SET IDENTITY_INSERT TEMPOEMPLEADOS ON
 IF UPDATE(ESTADO)
 BEGIN
	
	UPDATE EMPLEADOS SET ESTADO=0 WHERE ID_EMPLEADO=(SELECT ID_EMPLEADO FROM inserted);
 
    
	INSERT INTO TEMPOEMPLEADOS (ID_EMPLEADO,CODIGO_EMPLEADO, PRIMER_NOMBRE, PRIMER_APELLIDO,TELEFONO,SEGUNDO_NOMBRE,SEGUNDO_APELLIDO, CORREO,CEDULA,TIPO_EMPLEADO, DIRECCION, TELEFONO_EMERGENCIA, PARENTESCO) 
	(SELECT ID_EMPLEADO,CODIGO_EMPLEADO, PRIMER_NOMBRE, PRIMER_APELLIDO,TELEFONO,SEGUNDO_NOMBRE,SEGUNDO_APELLIDO, CORREO,CEDULA,TIPO_EMPLEADO, DIRECCION, TELEFONO_EMERGENCIA, PARENTESCO FROM deleted WHERE ID_EMPLEADO=deleted.ID_EMPLEADO);
 
 END;

 GO

 --PROCEDIMIENTO ALMACENADO DE CREAR EMPLEADO
--(C)

CREATE procedure CREAREMPLEADO
 @CODIGO_EMPLEADO CHAR(10), 
 @PRIMER_NOMBRE VARCHAR(50), 
 @PRIMER_APELLIDO VARCHAR(50), 
 @TELEFONO CHAR(8), 
 @SEGUNDO_NOMBRE VARCHAR(50), 
 @SEGUNDO_APELLIDO VARCHAR(50), 
 @CORREO VARCHAR(50), 
 @CEDULA VARCHAR(16), 
 @TIPO_EMPLEADO VARCHAR(50), 
 @DIRECCION VARCHAR(MAX), 
 @TELEFONO_EMERGENCIA CHAR(8), 
 @PARENTESCO VARCHAR(50)
as
declare @idcl as char(10)
set @idcl=(select CODIGO_EMPLEADO from EMPLEADOS where CODIGO_EMPLEADO=@CODIGO_EMPLEADO)
declare @pdt as char(1)
set @pdt=(select substring(@TELEFONO,1,1))
if(@CODIGO_EMPLEADO='' or @PRIMER_NOMBRE='' or  @PRIMER_APELLIDO='' or  @TELEFONO='' or @SEGUNDO_NOMBRE= '' or @CORREO='' or @CEDULA='' or @TIPO_EMPLEADO = '' or @DIRECCION = '' or @TELEFONO_EMERGENCIA='' or @PARENTESCO='')
begin
  print 'No pueden ser nulos'
end
else
begin
  if(@CODIGO_EMPLEADO=@idcl)
  begin
    print 'Cliente ya registrado'
  end
  else
  begin
    if(@pdt='2' or @pdt='5' or @pdt='7' or @pdt='8')
	begin
    INSERT INTO EMPLEADOS 
    VALUES (@CODIGO_EMPLEADO, @PRIMER_NOMBRE, @PRIMER_APELLIDO, @TELEFONO, @SEGUNDO_NOMBRE, @SEGUNDO_APELLIDO, @CORREO, @CEDULA, @TIPO_EMPLEADO, @DIRECCION, @TELEFONO_EMERGENCIA, @PARENTESCO,1)
	end
	else
	begin
	  print 'Debe iniciar con 2, 5, 7 u 8'
	end
  end
end
go

CREAREMPLEADO 'as-2343-23','Alvaro','Estrada','78654321','Antonio','Gonzalez','ealvaroestrad180@gmail.com','001-291001-1074H','Administracion','Waspna sur','87563490','Padre'
go

--PROCEDIMIENTO ALMACENADO DE MOSTRAR EMPLEADOS
--R
CREATE PROC MOSTRAREMPLEADOS
AS
     SELECT ID_EMPLEADO AS ID, CODIGO_EMPLEADO AS 'Cod Empleado', PRIMER_NOMBRE AS 'Primer nombre', PRIMER_APELLIDO AS 'Primer apellido', TELEFONO
	 AS 'Telefono', SEGUNDO_NOMBRE AS 'Segundo nombre', SEGUNDO_APELLIDO AS 'Segundo apellido', CORREO AS 'Correo', CEDULA AS 'Cedula', TIPO_EMPLEADO AS 'Tipo empleado',
	 DIRECCION AS 'Direccion', TELEFONO AS 'Tel Emergencia', PARENTESCO AS 'Parentesco' FROM EMPLEADOS WHERE ESTADO=1 
GO

--PROCEDIMIENTO ALMACENADO EDITAR EMPLEADO
-- U
create PROC EDITAREMPLEADO
@ID INT,
@CORREO VARCHAR(50),
@TELEFONO CHAR(8),
@DIRECCION VARCHAR(MAX),
@T_EMERGENCIA CHAR(8)

AS
  IF EXISTS (SELECT ID_EMPLEADO FROM EMPLEADOS WHERE @ID=ID_EMPLEADO)
  BEGIN
	   UPDATE EMPLEADOS SET CORREO=@CORREO WHERE @ID=ID_EMPLEADO
	   UPDATE EMPLEADOS SET TELEFONO=@TELEFONO WHERE @ID=ID_EMPLEADO
	   UPDATE EMPLEADOS SET DIRECCION = @DIRECCION WHERE @ID=ID_EMPLEADO
	   UPDATE EMPLEADOS SET TELEFONO_EMERGENCIA = @T_EMERGENCIA WHERE @ID=ID_EMPLEADO
  END
    
GO

  --PROCEDIMIENTO ALMACENADO PARA DAR DE BAJA A UN USARIO
  --(D) 
 create PROC BAJAEMPLEADO
@codEmpleado varchar(10)
AS
    
	IF EXISTS (SELECT CODIGO_EMPLEADO FROM EMPLEADOS WHERE CODIGO_EMPLEADO=@codEmpleado)
  BEGIN
       UPDATE EMPLEADOS SET ESTADO=0 where CODIGO_EMPLEADO=@codEmpleado
  END

GO

-- PROCEDIMIENTO ALMACENADO PARA DAR DE ALTA AL EMPLEADO
CREATE PROCEDURE ALTAEMPLEADO
@ID CHAR(3)
AS
DECLARE  @IDCL CHAR(3)
SET @IDCL=(SELECT ID_EMPLEADO FROM EMPLEADOS WHERE ID_EMPLEADO=@ID)
IF(@ID='')
BEGIN
  PRINT 'NO PUEDE SER NULO'
END
ELSE
BEGIN
  IF(@ID=@IDCL)
  BEGIN
    UPDATE EMPLEADOS SET ESTADO=1 WHERE ID_EMPLEADO=@ID and
	ESTADO=0
  END
  ELSE
  BEGIN
    PRINT 'NO REGISTRADO'
  END
END
GO

CREATE PROC BUSCAEMPLEADOS
@CODIGO_EMPLEADO VARCHAR(10)
AS
SELECT ID_EMPLEADO AS ID, CODIGO_EMPLEADO AS 'Cod Empleado', PRIMER_NOMBRE AS 'Primer nombre', PRIMER_APELLIDO AS 'Primer apellido', TELEFONO
	 AS 'Telefono', SEGUNDO_NOMBRE AS 'Segundo nombre', SEGUNDO_APELLIDO AS 'Segundo apellido', CORREO AS 'Correo', CEDULA AS 'Cedula', TIPO_EMPLEADO AS 'Tipo empleado',
	 DIRECCION AS 'Direccion', TELEFONO AS 'Tel Emergencia', PARENTESCO AS 'Parentesco' FROM EMPLEADOS WHERE CODIGO_EMPLEADO = @CODIGO_EMPLEADO
GO


-- PROCEDIMIENTO DE FILTAR BUSQUEDA DE EMPLEADO POR CEDULA
CREATE PROC BUSCEDULA 
@CEDULA VARCHAR(16)
AS
SELECT ID_EMPLEADO AS ID, CODIGO_EMPLEADO AS 'Cod Empleado', PRIMER_NOMBRE AS 'Primer nombre', PRIMER_APELLIDO AS 'Primer apellido', TELEFONO
	 AS 'Telefono', SEGUNDO_NOMBRE AS 'Segundo nombre', SEGUNDO_APELLIDO AS 'Segundo apellido', CORREO AS 'Correo', CEDULA AS 'Cedula', TIPO_EMPLEADO AS 'Tipo empleado',
	 DIRECCION AS 'Direccion', TELEFONO AS 'Tel Emergencia', PARENTESCO AS 'Parentesco' FROM EMPLEADOS WHERE CEDULA = @CEDULA
GO

-- PROCEDIMIENTO DE FILTAR BUSQUEDA DE EMPLEADO POR CEDULA
Create PROC CODEMPLEADO
@CODIGO_EMPLEADO VARCHAR(10)
AS
SELECT *  FROM EMPLEADOS WHERE CODIGO_EMPLEADO = @CODIGO_EMPLEADO 
GO



--------------------------------------PROVEEDOR-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--CREANDO TABLA PROVEEDOR
CREATE TABLE PROVEEDOR(
ID_PROVEEDOR INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NOMBRE_PROVE VARCHAR (50) NOT NULL,
APELLIDO_PROV VARCHAR (50) NOT NULL,
TELEFONO CHAR (8) CHECK (TELEFONO like '[5|7|8][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') not null, 
DIRECCION_EMPRESA VARCHAR (MAX) NOT NULL,
NOMBRE_EMPRESA VARCHAR (50),
ESTADO BIT DEFAULT 1
)
GO

--CREANDO TABLA TEMPORAL DE PROVEEDOR
CREATE TABLE TEMPOPROVEEDOR(
ID_PROVEEDOR INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NOMBRE_PROVE VARCHAR (50) NOT NULL,
APELLIDO_PROV VARCHAR (50) NOT NULL,
TELEFONO CHAR (8) CHECK (TELEFONO like '[5|7|8][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') not null, 
DIRECCION_EMPRESA VARCHAR (MAX) NOT NULL,
NOMBRE_EMPRESA VARCHAR (50),
ESTADO BIT DEFAULT 0
)
GO
 --PROCEDIMIENTO ALMACENADO DE MOSTRAR PROVEEDOR
--(C)
CREATE PROC MOSTRARPROVEEDORES
AS
     SELECT ID_PROVEEDOR AS 'Id proveedor', NOMBRE_PROVE AS 'Nombre Proveedor', APELLIDO_PROV AS 'Apellido Proveedor', TELEFONO AS 'Telefono', DIRECCION_EMPRESA
	 AS 'Dir. Empresa', NOMBRE_EMPRESA AS 'Empresa'  FROM PROVEEDOR WHERE ESTADO=1 
GO
 --PROCEDIMIENTO ALMACENADO DE CREAR PROVEEDOR
--(C)

CREATE PROC CREARPROVEEDOR
@NOMBRE_PROV VARCHAR(50), 
@APELLIDO_PROV VARCHAR(50), 
@TELEFONO CHAR(8), 
@DIRECCION_EMPRESA VARCHAR(MAX), 
@NOMBRE_EMPRESA VARCHAR(50)
AS
   INSERT INTO PROVEEDOR(NOMBRE_PROVE, APELLIDO_PROV, TELEFONO, DIRECCION_EMPRESA, NOMBRE_EMPRESA)
   VALUES (@NOMBRE_PROV, @APELLIDO_PROV, @TELEFONO, @DIRECCION_EMPRESA, @NOMBRE_EMPRESA)
GO
CREARPROVEEDOR 'Juan','Rivera','87563498','Mercado oriental','CONMEMA'
GO
--PROCEDIMIENTO ALMACENADO PARA BUSQUEDA POR FILTROS TABLA PROVEEDOR
--R

--BUSCAR POR NOMBRE DE EMPRESA
CREATE PROC NOMBREEMPRESA
AS

SELECT DISTINCT NOMBRE_EMPRESA FROM PROVEEDOR
GO

-- BUSCAR POR NOMBRE DEL PROVEEDOR 
CREATE PROC NOMBREPROVEEDOR
AS
SELECT DISTINCT NOMBRE_PROVE FROM PROVEEDOR
GO

 --PROCEDIMIENTO ALMACENADO PARA DAR DE BAJA A UN PROVEEDOR
  --(D) 
 CREATE PROC BAJAPROVEEDOR
@ID INT
AS
    
	IF EXISTS (SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE ID_PROVEEDOR=@ID)
  BEGIN
       UPDATE PROVEEDOR SET ESTADO=0 where ID_PROVEEDOR=@ID
  END

GO

-- PROCEDIMIENTO ALMACENADO PARA DAR DE ALTA A UN PROVEEDOR 
CREATE PROC ALTAPROVEEDOR
@ID CHAR(3)
AS
DECLARE  @IDP CHAR(3)
SET @IDP=(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE ID_PROVEEDOR=@ID)
IF(@ID='')
BEGIN
  PRINT 'NO PUEDE SER NULO'
END
ELSE
BEGIN
  IF(@ID=@IDP)
  BEGIN
    UPDATE PROVEEDOR SET ESTADO=1 WHERE ID_PROVEEDOR=@ID and
	ESTADO=0
  END
  ELSE
  BEGIN
    PRINT 'NO REGISRTRADO'
  END
END
GO

------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------PRODUCTOS-------------------------------------------------------------------------------------------------------
--CREACION DE TABLA PRODUCTO 

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
COD_PRODUCTO VARCHAR(12) NOT NULL,
NOMBRE_PRODUCTO VARCHAR(100) NOT NULL,
CATEGORIA VARCHAR(50) NOT NULL,
PRECIO_COMPRA FLOAT NOT NULL,
PRECIO_VENTA FLOAT NOT NULL,
MARCA VARCHAR(30) NOT NULL,
ID_PROVEEDOR INT FOREIGN KEY REFERENCES PROVEEDOR(ID_PROVEEDOR) NOT NULL,
DESCRIPCION VARCHAR(MAX) NOT NULL,
CANTIDAD_DISPONIBLE INT NOT NULL,
ALMACEN VARCHAR(50) CHECK (ALMACEN = 'Bodega 1' OR ALMACEN = 'Bodega 2') NOT NULL,
ESTADO BIT DEFAULT 1
)
GO
-- CREACION DE TABLA TEMPORAL DE PRODUCTO
CREATE TABLE TEMPOPRODUCTOS(
ID_PRODUCTO INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
COD_PRODUCTO VARCHAR(12) NOT NULL,
NOMBRE_PRODUCTO VARCHAR(100) NOT NULL,
CATEGORIA VARCHAR(50) NOT NULL,
PRECIO_COMPRA FLOAT NOT NULL,
PRECIO_VENTA FLOAT NOT NULL,
MARCA VARCHAR(30) NOT NULL,
ID_PROVEEDOR INT FOREIGN KEY REFERENCES PROVEEDOR(ID_PROVEEDOR) NOT NULL,
DESCRIPCION VARCHAR(MAX) NOT NULL,
CANTIDAD_DISPONIBLE INT NOT NULL,
ALMACEN VARCHAR(50) CHECK (ALMACEN = 'Bodega 1' OR ALMACEN = 'Bodega 2') NOT NULL,
ESTADO BIT DEFAULT 0
)
GO
-- PROCEDIMIENTO ALMACENADO DE INSERTAR PRODUCTO
create PROC INSERPRODUCTO
@COD_PRODUCTO VARCHAR(12),
@NOMBRE_PRODUCTO VARCHAR(100), 
@CATEGORIA VARCHAR(50), 
@PRECIO_COMPRA FLOAT, 
@PRECIO_VENTA FLOAT, 
@MARCA VARCHAR(30),
@proveedor int, 
@DESCRIPCION VARCHAR(MAX), 
@CANTIDAD_DISPONIBLE INT, 
@ALMACEN VARCHAR(50)
AS
declare @idproveedor int 
set @idproveedor=(select ID_PROVEEDOR from PROVEEDOR where ID_PROVEEDOR=@proveedor)
INSERT INTO PRODUCTOS (COD_PRODUCTO,NOMBRE_PRODUCTO, CATEGORIA, PRECIO_COMPRA, PRECIO_VENTA, MARCA,ID_PROVEEDOR, DESCRIPCION, CANTIDAD_DISPONIBLE, ALMACEN) 
VALUES(@COD_PRODUCTO ,@NOMBRE_PRODUCTO, @CATEGORIA, @PRECIO_COMPRA, @PRECIO_VENTA,@MARCA,@idproveedor,@DESCRIPCION,@CANTIDAD_DISPONIBLE,@ALMACEN )
GO


INSERPRODUCTO 'K-34-34','Aceite','Moto',345,448.5,'Jirasol',1,'Aceite para moto',3,'Bodega 1'
go
CREATE PROC MOSTRARPRODUCTOS
AS
     SELECT ID_PRODUCTO as Numero, COD_PRODUCTO as 'Cod. Producto',NOMBRE_PRODUCTO as 'Nombre',CATEGORIA as 'Categoria',PRECIO_COMPRA as 'Precio de compra',PRECIO_VENTA as 'Precio de venta',
		MARCA as 'Marca',ID_PROVEEDOR as 'Id de proveedor',DESCRIPCION as 'Descripcion',CANTIDAD_DISPONIBLE as 'Cantidad',ALMACEN as 'Almacen' FROM PRODUCTOS WHERE ESTADO=1 
GO

CREATE PROC BUSCARCODPRODUCTO
@COD_PRODUCTO varchar(12)
AS
SELECT ID_PRODUCTO as Numero, COD_PRODUCTO as 'Cod. Producto',NOMBRE_PRODUCTO as 'Nombre',CATEGORIA as 'Categoria',PRECIO_COMPRA as 'Precio de compra',PRECIO_VENTA as 'Precio de venta',
MARCA as 'Marca',ID_PROVEEDOR as 'Id de proveedor',DESCRIPCION as 'Descripcion',CANTIDAD_DISPONIBLE as 'Cantidad',ALMACEN as 'Almacen' FROM PRODUCTOS
GO

--PROCEDIMIENTO ALMACENADO EDITAR PRODUCTOS
-- U
CREATE PROC EDITPRODUCTOS
@COD_PRODUCTO varchar(12),
@PRECIO_COMPRA FLOAT,
@PRECIO_VENTA FLOAT 
AS
  IF EXISTS (SELECT COD_PRODUCTO FROM PRODUCTOS WHERE COD_PRODUCTO=@COD_PRODUCTO)
  BEGIN
	   UPDATE PRODUCTOS SET PRECIO_COMPRA =@PRECIO_COMPRA WHERE ID_PRODUCTO=@COD_PRODUCTO
	   UPDATE PRODUCTOS SET PRECIO_VENTA =@PRECIO_VENTA WHERE ID_PRODUCTO=@COD_PRODUCTO
  END 
GO

 --PROCEDIMIENTO ALMACENADO PARA DAR DE BAJA A UN PRODUCTO
  --(D) 
 CREATE PROC BAJAPRODUCTO
@COD_PRODUCTO varchar(12)
AS    
	IF EXISTS (SELECT COD_PRODUCTO FROM PRODUCTOS WHERE COD_PRODUCTO=@COD_PRODUCTO)
  BEGIN
       UPDATE PRODUCTOS SET ESTADO=0 WHERE COD_PRODUCTO=@COD_PRODUCTO
  END

GO

-- PROCEDIMIENTO ALMACENADO PARA DAR DE ALTA AL PRODUCTO
CREATE PROC ALTAPRODUCTO
@ID CHAR(3)
AS
DECLARE  @IDP CHAR(3)
SET @IDP=(SELECT ID_PRODUCTO FROM PRODUCTOS WHERE ID_PRODUCTO=@ID)
IF(@ID='')
BEGIN
  PRINT 'NO PUEDE SER NULO'
END
ELSE
BEGIN
  IF(@ID=@IDP)
  BEGIN
    UPDATE PRODUCTOS SET ESTADO=1 WHERE ID_PRODUCTO=@ID and
	ESTADO=0
  END
  ELSE
  BEGIN
    PRINT 'NO REGISRTRADO'
  END
END
GO
CREATE PROC BUSCODIGOPRODUCTO
@CODIGO VARCHAR(16)
AS
SELECT ID_PRODUCTO as Numero, COD_PRODUCTO as 'Cod. Producto',NOMBRE_PRODUCTO as 'Nombre',CATEGORIA as 'Categoria',PRECIO_COMPRA as 'Precio de compra',PRECIO_VENTA as 'Precio de venta',
MARCA as 'Marca',ID_PROVEEDOR as 'Id de proveedor',DESCRIPCION as 'Descripcion',CANTIDAD_DISPONIBLE as 'Cantidad',ALMACEN as 'Almacen' FROM PRODUCTOS WHERE COD_PRODUCTO = @CODIGO
GO
--------------------------------------USUARIOS-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--CREACION DE TABLA USUARIOS
CREATE TABLE USUARIOS(
ID_USUARIO INT IDENTITY(2001,1) PRIMARY KEY NOT NULL,
CODIGO_EMPLEADO VARCHAR(10) NOT NULL,
PRIMER_NOMBRE VARCHAR(20) NOT NULL,
PRIMER_APELLIDO VARCHAR(20) NOT NULL,
TIPO_USUARIO VARCHAR (50) NOT NULL,
USUARIO VARCHAR (20) NOT NULL,
CONTRA VARCHAR(50) NOT NULL,
ID_EMPLEADO INT FOREIGN KEY REFERENCES  EMPLEADOS(ID_EMPLEADO) NOT NULL,
ESTADO BIT DEFAULT 1
)
GO 

--CREACION DE TABLA TEMPORAL DE USUARIOS
CREATE TABLE TEMPOUSUARIOS(
ID_USUARIO INT IDENTITY(2001,1) PRIMARY KEY NOT NULL,
CODIGO_EMPLEADO VARCHAR(10) NOT NULL,
PRIMER_NOMBRE VARCHAR(20) NOT NULL,
PRIMER_APELLIDO VARCHAR(20) NOT NULL,
TIPO_USUARIO VARCHAR (50) NOT NULL,
USUARIO VARCHAR (20) NOT NULL,
CONTRA VARCHAR(50) NOT NULL,
ID_EMPLEADO INT FOREIGN KEY REFERENCES  TEMPOEMPLEADOS(ID_EMPLEADO) NOT NULL,
ESTADO BIT DEFAULT 0
)
GO


---PROCEDIMIENTO ALMACENADOS DE LA TABLA USUARIOS

--PROCEDIMIENTO ALMACENADO DE CREAR USUARIOS
--(C)

create PROC CREARUSUARIO
@CODIGO_EMPLEADO VARCHAR(10),
@TIPO_USUARIO VARCHAR(50), 
@USUARIO VARCHAR(50), 
@CONTRA VARCHAR(50)
AS
DECLARE @PRIMER_NOMBRE VARCHAR (20) 
DECLARE @PRIMER_APELLIDO VARCHAR (20)
DECLARE @ID_EMPLEADO INT 
    SET @PRIMER_NOMBRE = (SELECT PRIMER_NOMBRE FROM EMPLEADOS WHERE @CODIGO_EMPLEADO = CODIGO_EMPLEADO)
	SET @PRIMER_APELLIDO = (SELECT PRIMER_APELLIDO FROM EMPLEADOS WHERE @CODIGO_EMPLEADO = CODIGO_EMPLEADO)
	SET @ID_EMPLEADO = (SELECT ID_EMPLEADO FROM EMPLEADOS WHERE @CODIGO_EMPLEADO = CODIGO_EMPLEADO)
    INSERT INTO USUARIOS (CODIGO_EMPLEADO, PRIMER_NOMBRE,PRIMER_APELLIDO, TIPO_USUARIO, USUARIO, CONTRA,ID_EMPLEADO)
    VALUES (@CODIGO_EMPLEADO, @PRIMER_NOMBRE, @PRIMER_APELLIDO, @TIPO_USUARIO, @USUARIO, @CONTRA,@ID_EMPLEADO) 
GO

CREARUSUARIO 'as-2343-23','Administrador','fernando','123'
go
--PROCEDIMIENTO ALMACENADO DE MOSTRAR USUARIOS
--R
CREATE PROC BUSCARTIPOUSUARIO
@TIPO_USUARIO VARCHAR(20)
AS
DECLARE @USUARIO VARCHAR(20)
SET @USUARIO = (SELECT TIPO_USUARIO FROM USUARIOS WHERE TIPO_USUARIO = @TIPO_USUARIO)
IF(@USUARIO= @TIPO_USUARIO)
BEGIN
  PRINT 'NO PUEDE SER NULO'
END
ELSE
BEGIN
	SELECT ID_USUARIO AS 'Id usuario', CODIGO_EMPLEADO AS 'Cod Empleado', PRIMER_NOMBRE AS 'Primer nombre', PRIMER_APELLIDO AS 'Primer apellido', TIPO_USUARIO
	 AS 'Tipo de acceso', USUARIO AS 'Usuario de acceso', CONTRA AS 'Contraseña',
	 ID_EMPLEADO AS 'ID empleado'FROM USUARIOS WHERE TIPO_USUARIO = @TIPO_USUARIO
  END
GO

-- PROCEDIMIENTO PARA BUSCAR USUARIO POR CODIGO DE EMPLEADO 
create PROC BUSCARUSUARIOCODIGO
@CODIGO_EMPLEADO VARCHAR(20)
AS
DECLARE @USUARIO VARCHAR(20)
SET @USUARIO = (SELECT CODIGO_EMPLEADO FROM USUARIOS WHERE CODIGO_EMPLEADO = @CODIGO_EMPLEADO)
IF(@USUARIO= @CODIGO_EMPLEADO)
BEGIN
  PRINT 'NO PUEDE SER NULO'
END
ELSE
BEGIN
	SELECT ID_EMPLEADO AS 'Numero de registro de empleado', CODIGO_EMPLEADO AS 'Cod Empleado', PRIMER_NOMBRE AS 'Primer nombre', PRIMER_APELLIDO AS 'Primer apellido' FROM EMPLEADOS WHERE CODIGO_EMPLEADO = @CODIGO_EMPLEADO
  END
GO
--PROCEDIMIENTO ALMACENADO EDITAR USUARIO
-- U ELEIMINE EL PODER EDITAR LA FOTO DEL EMPLEADO
CREATE PROC EDITUSUARIO
@CODIGO_EMPLEADO VARCHAR(10),
@CONTRA VARCHAR(50)
AS
  IF EXISTS (SELECT ID_USUARIO FROM USUARIOS WHERE CODIGO_EMPLEADO=@CODIGO_EMPLEADO)
  BEGIN
	   UPDATE USUARIOS SET CONTRA=@CONTRA WHERE CODIGO_EMPLEADO=@CODIGO_EMPLEADO

  END
    
GO

  --PROCEDIMIENTO ALMACENADO PARA DAR DE BAJA A UN USARIO
  --(D) 
 CREATE PROC BAJAUSUARIO
@COD_EMPLEADO VARCHAR(10)
AS
    
	IF EXISTS (SELECT CODIGO_EMPLEADO FROM USUARIOS WHERE CODIGO_EMPLEADO=@COD_EMPLEADO)
  BEGIN
       UPDATE USUARIOS SET ESTADO=0 where CODIGO_EMPLEADO=@COD_EMPLEADO
  END

GO

-- PROCEDIMIENTO ALMACENADO PARA DAR DE ALTA AL USARIOS
CREATE PROCEDURE ALTAUSUARIO
@ID CHAR(3)
AS
DECLARE  @IDCL CHAR(3)
SET @IDCL=(SELECT ID_USUARIO FROM USUARIOS WHERE ID_USUARIO=@ID)
IF(@ID='')
BEGIN
  PRINT 'NO PUEDE SER NULO'
END
ELSE
BEGIN
  IF(@ID=@IDCL)
  BEGIN
    UPDATE USUARIOS SET ESTADO=1 WHERE ID_USUARIO=@ID and
	ESTADO=0
  END
  ELSE
  BEGIN
    PRINT 'NO REGISTRADO'
  END
END
GO


--LISTAR USUARIOS 
CREATE PROC MOSTRARUSUARIOS
AS
     SELECT ID_USUARIO AS 'Id usuario', CODIGO_EMPLEADO AS 'Cod Empleado', PRIMER_NOMBRE AS 'Primer nombre', PRIMER_APELLIDO AS 'Primer apellido', TIPO_USUARIO
	 AS 'Tipo de acceso', USUARIO AS 'Usuario de acceso', CONTRA AS 'Contraseña',
	 ID_EMPLEADO AS 'ID empleado' FROM USUARIOS WHERE ESTADO=1 
GO
CREATE PROC MOSTRAREmpleado
AS
     SELECT ID_EMPLEADO AS 'Numero de registro de empleado', CODIGO_EMPLEADO AS 'Cod Empleado', 
	 PRIMER_NOMBRE AS 'Primer nombre', PRIMER_APELLIDO AS 'Primer apellido' FROM EMPLEADOS WHERE ESTADO=1 
GO

------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------MAQUINARIAS-----------------------------------------------------------------------------------------------------

CREATE TABLE MAQUINARIAS
(
ID_MAQUINARIA INT IDENTITY (1001,1) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
CATEGORIA VARCHAR(20)CHECK (CATEGORIA = 'Moto' OR CATEGORIA = 'Vehiculo Liviano') NOT NULL,
IDENTIFICADOR VARCHAR(12) CHECK( IDENTIFICADOR LIKE '[0-9][0-9][0-9]-[0-9][0-9][0-9]' ),
AREA VARCHAR (20) CHECK (AREA = 'Mecanica' OR AREA = 'Lavado') NOT NULL,
TIPO VARCHAR (20) CHECK (TIPO = 'Herramienta' OR TIPO = 'Maquina') NOT NULL,
ALMACEN VARCHAR(50) CHECK (ALMACEN = 'Bodega 1' OR ALMACEN = 'Bodega 2') NOT NULL,
FECHA DATETIME,
ESTADO BIT DEFAULT 1
)


CREATE TABLE TEMPOMAQUINARIAS
(
ID_MAQUINARIA INT IDENTITY (1001,1) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
CATEGORIA VARCHAR(20)CHECK (CATEGORIA = 'Moto' OR CATEGORIA = 'Vehiculo Liviano') NOT NULL,
IDENTIFICADOR VARCHAR(12) CHECK( IDENTIFICADOR LIKE '[0-9][0-9][0-9]-[0-9][0-9][0-9]' ),
AREA VARCHAR (20) CHECK (AREA = 'Mecanica' OR AREA = 'Lavado') NOT NULL,
TIPO VARCHAR (20) CHECK (TIPO = 'Herramienta' OR TIPO = 'Maquina') NOT NULL,
ALMACEN VARCHAR (15) CHECK (ALMACEN = 'Bodega 1' OR ALMACEN = 'Bodega 2') NOT NULL,
FECHA DATETIME,
ESTADO BIT DEFAULT 0
)
GO
--TRIGGER DE MAQUINARIA
CREATE  TRIGGER ESTADOMAQUINA
ON MAQUINARIAS
 AFTER UPDATE AS 

 SET IDENTITY_INSERT TEMPOMAQUINARIAS ON
 IF UPDATE(ESTADO)
 BEGIN
	
	UPDATE MAQUINARIAS SET ESTADO=0 WHERE ID_MAQUINARIA =(SELECT ID_MAQUINARIA FROM inserted);
 
    
	INSERT INTO TEMPOMAQUINARIAS (ID_MAQUINARIA, NOMBRE, CATEGORIA, IDENTIFICADOR, AREA, TIPO,ALMACEN, FECHA)
	(SELECT ID_MAQUINARIA, NOMBRE, CATEGORIA, IDENTIFICADOR, AREA, TIPO, ALMACEN, FECHA FROM deleted WHERE ID_MAQUINARIA=deleted.ID_MAQUINARIA);
 
 END;

 GO

 -- MOSTRAR MAQUINARIA

CREATE PROC MOSTRARMAQUINARIA
AS
SELECT ID_MAQUINARIA as 'Numero de registro' ,NOMBRE AS 'Nombre', CATEGORIA as 'Categoria', IDENTIFICADOR as 'Identificador', AREA as 'Area', TIPO as 'Tipo' , ALMACEN as 'Almacen', 
FECHA as 'Fecha de registro' FROM MAQUINARIAS where ESTADO=1
GO

--REGISTRAR MAQUINARIA
create PROC INGRESARMAQUINA
@NOMBRE VARCHAR(20), 
@CATEGORIA VARCHAR(20), 
@IDENTIFICADOR VARCHAR(12), 
@AREA VARCHAR(20), 
@TIPO VARCHAR(20), 
@ALMACEN VARCHAR(50),
@FECHA datetime
as
declare @idcl as char(10)
set @idcl=(select IDENTIFICADOR from MAQUINARIAS where IDENTIFICADOR=@IDENTIFICADOR)
declare @pdt as char(1)
if(@NOMBRE='' or @CATEGORIA='' or  @IDENTIFICADOR='' or  @AREA='' or @TIPO= '' OR  @ALMACEN=''OR  @FECHA='')
begin
  print 'No pueden ser nulos'
end
else
begin
  if(@IDENTIFICADOR=@idcl)
  begin
    print 'Maquina ya registrado'
  end
  else
    INSERT INTO MAQUINARIAS (NOMBRE,CATEGORIA,IDENTIFICADOR,AREA,TIPO,ALMACEN,FECHA)
    VALUES(@NOMBRE, @CATEGORIA, @IDENTIFICADOR, @AREA, @TIPO,@ALMACEN,@FECHA)
  end
go


--EDITAR MAQUINARIA
CREATE PROC EDITARMAQUINARIA
@IDentificador varchar(15),
@ALMACEN VARCHAR(15)
AS
	IF EXISTS( SELECT IDENTIFICADOR FROM MAQUINARIAS WHERE IDENTIFICADOR=@IDentificador)
	BEGIN
		UPDATE MAQUINARIAS SET ALMACEN = @ALMACEN WHERE IDENTIFICADOR=@IDentificador

	END
GO

--PROCEDIMIENTO ALMACENADO PARA DAR DE BAJA A LA MAQUINARIA
  --(D) 
 CREATE PROC BAJAMAQUINARIA
@IDentificador varchar(15)
AS
    
	IF EXISTS( SELECT IDENTIFICADOR FROM MAQUINARIAS WHERE IDENTIFICADOR=@IDentificador)
  BEGIN
       UPDATE MAQUINARIAS SET ESTADO=0 where IDENTIFICADOR=@IDentificador
  END

GO

-- PROCEDIMIENTO ALMACENADO PARA DAR DE ALTA A LA MAQUINARIA
CREATE PROCEDURE ALTAMAQUINARIA
@ID CHAR(3)
AS
DECLARE  @IDCL CHAR(3)
SET @IDCL=(SELECT ID_MAQUINARIA FROM MAQUINARIAS WHERE ID_MAQUINARIA=@ID)
IF(@ID='')
BEGIN
  PRINT 'NO PUEDE SER NULO'
END
ELSE
BEGIN
  IF(@ID=@IDCL)
  BEGIN
    UPDATE MAQUINARIAS SET ESTADO=1 WHERE ID_MAQUINARIA=@ID and
	ESTADO=0
  END
  ELSE
  BEGIN
    PRINT 'NO REGISTRADO'
  END
END
GO

-- BUSCAR POR identificador
CREATE PROC BUSCARIDENTIFICADORMAQUINA
@identicador VARCHAR(10)
AS
SELECT ID_MAQUINARIA as 'Numero de registro' ,NOMBRE AS 'Nombre', CATEGORIA as 'Categoria', IDENTIFICADOR as 'Identificador', AREA as 'Area', TIPO as 'Tipo' , ALMACEN as 'Almacen', 
FECHA as 'Fecha de registro' FROM MAQUINARIAS WHERE IDENTIFICADOR = @identicador
GO



----------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------CLIENTE-------------------------------------------------------------------------------------------------------

-- TABLA CLIENTE
CREATE TABLE CLIENTES
(
ID_CLIENTE INT IDENTITY (3001,1) PRIMARY KEY NOT NULL,
NOMBRE_CLIENTE VARCHAR(20) NOT NULL,
APELLIDO_CLIENTE VARCHAR(20) NOT NULL,
PLACA_AUTO VARCHAR(10) CHECK(PLACA_AUTO = '[A-Z] [0-9][0-9][0-9]-[0-9][0-9][0-9]') NOT NULL, 
ESTADO BIT DEFAULT 1 
)
GO

CREATE TABLE TEMPOCLIENTES
(
ID_CLIENTE INT IDENTITY (3001,1) PRIMARY KEY NOT NULL,
NOMBRE_CLIENTE VARCHAR(20) NOT NULL,
APELLIDO_CLIENTE VARCHAR(20) NOT NULL,
PLACA_AUTO VARCHAR(10) CHECK(PLACA_AUTO = '[A-Z] [0-9][0-9][0-9]-[0-9][0-9][0-9]') NOT NULL, 
ESTADO BIT DEFAULT 0 
)
GO

CREATE  TRIGGER ESTADOCLIENTE
ON CLIENTES
 AFTER UPDATE AS 

 SET IDENTITY_INSERT TEMPOMAQUINARIAS ON
 IF UPDATE(ESTADO)
 BEGIN
	
	UPDATE TEMPOCLIENTES SET ESTADO=0 WHERE ID_CLIENTE =(SELECT ID_CLIENTE FROM inserted);
 
    
	INSERT INTO TEMPOCLIENTES (ID_CLIENTE, NOMBRE_CLIENTE, APELLIDO_CLIENTE, PLACA_AUTO)
	(SELECT ID_CLIENTE, NOMBRE_CLIENTE, APELLIDO_CLIENTE, PLACA_AUTO FROM deleted WHERE ID_CLIENTE=deleted.ID_CLIENTE);
 
 END;

 GO
 CREATE PROC MOSTRARCLIENTES
AS
SELECT ID_CLIENTE as 'Numero de registro' ,NOMBRE_CLIENTE AS 'Nombre de cliente', APELLIDO_CLIENTE as 'Apellido de cliente', PLACA_AUTO as 'Placa de auto' FROM CLIENTES where ESTADO=1
GO



-- AGREGAR CLIENTE PROC
CREATE PROC AGREGARCLIENTE
@NOMBRE_CLIENTE VARCHAR(20),
@APELLIDO_CLIENTE VARCHAR(20),
@PLACA_AUTO VARCHAR(10)
AS
declare @idcl as char(10)
set @idcl=(select PLACA_AUTO from CLIENTES where PLACA_AUTO=@PLACA_AUTO)
if(@PLACA_AUTO=@idcl)
  begin
    print 'Cliente ya registrado'
  end
  else
  begin
	INSERT INTO CLIENTES (NOMBRE_CLIENTE, APELLIDO_CLIENTE, PLACA_AUTO) VALUES (@NOMBRE_CLIENTE, @APELLIDO_CLIENTE, @PLACA_AUTO)
 end
GO

--EDITAR CLIENTE
CREATE PROC EDITARCLIENTE
@ID INT,
@PLACA_AUTO VARCHAR(10)
AS
	IF EXISTS( SELECT ID_CLIENTE FROM CLIENTES WHERE ID_CLIENTE=@ID)
	BEGIN
		UPDATE CLIENTES SET PLACA_AUTO = @PLACA_AUTO WHERE ID_CLIENTE=@ID
	END
GO

--PROCEDIMIENTO ALMACENADO PARA DAR DE BAJA CLIENTE
  
 CREATE PROC BAJACLIENTE
@PLACA VARCHAR(15)
AS
    
	IF EXISTS (SELECT PLACA_AUTO FROM CLIENTES WHERE PLACA_AUTO=@PLACA)
  BEGIN
       UPDATE CLIENTES SET ESTADO=0 where PLACA_AUTO=@PLACA
  END

GO

-- BUSCAR CLIENTE POR PLACA DE AUTO 
CREATE PROC BUSQUEDACLIENTE
@PLACA_AUTO VARCHAR(10)
AS
SELECT * FROM CLIENTES WHERE PLACA_AUTO = @PLACA_AUTO
GO

-- BUSCAR CLIENTE POR CODIOGO DE CLIENTE [ID]
CREATE PROC BUSCARCLIENTEID
@ID INT
AS
SELECT * FROM CLIENTES WHERE ID_CLIENTE = @ID
GO

----------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------FACTURA-------------------------------------------------------------------------------------------------------

--CREANDO TABLA FACTURA
CREATE TABLE FACTURA(
ID_FACTURA INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
TOTAL FLOAT NOT NULL,
FECHA DATETIME NOT NULL,
USUARIO VARCHAR(20),
ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTOS(ID_PRODUCTO) NOT NULL,
ESTADO BIT DEFAULT 1
)
GO

CREATE TABLE TEMPOFACTURA(
ID_FACTURA INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
TOTAL FLOAT NOT NULL,
FECHA DATETIME NOT NULL,
USUARIO VARCHAR(20),
ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTOS(ID_PRODUCTO) NOT NULL,
ESTADO BIT DEFAULT 0
)
GO

---PROCEDIMIENTOS ALMACENADOS  Y TRIGGER DE LA TABLA FACTURA
-- CREACION DE UN TRIGER SOBRE LA TABLA FACTURA
CREATE  TRIGGER ESTADOFACTURA 
ON FACTURA
 AFTER UPDATE AS 

 SET IDENTITY_INSERT TEMPOFACTURA ON
 IF UPDATE(ESTADO)
 BEGIN
	
	UPDATE FACTURA SET ESTADO=0 WHERE ID_FACTURA=(SELECT ID_FACTURA FROM inserted);
 
    
	INSERT INTO TEMPOFACTURA (ID_FACTURA,TOTAL, FECHA,USUARIO,ID_PRODUCTO) 
	(SELECT ID_FACTURA,TOTAL,FECHA,USUARIO,ID_PRODUCTO FROM deleted WHERE ID_FACTURA=deleted.ID_FACTURA);
 END;
 GO

CREATE PROC MOSTRARFACTURAS
AS
 SELECT ID_FACTURA as 'Numero de registro' , TOTAL as 'Total', FECHA as 'Fecha', ID_PRODUCTO as 'Numero de producto', USUARIO as 'Usuario' FROM FACTURA where ESTADO=1
GO
--- CREAR FACTURA
create PROC CREARFACTURA
@TOTAL FLOAT,
@FECHA DATETIME,
@USUARIO VARCHAR(20)
as
DECLARE @IDPRO INT
SET @IDPRO=(select top 1 ID_PRODUCTO from PRODUCTOS order by ID_PRODUCTO desc)
if (@TOTAL=0.0 or @USUARIO= '' )
	BEGIN
		print 'NO PUEDEN SER NULOS'
	END
  ELSE
	begin
		INSERT INTO FACTURA ( TOTAL,FECHA, USUARIO,ID_PRODUCTO)
		VALUES ( @TOTAL, @FECHA, @USUARIO,@IDPRO)
	END

GO

 --PROCEDIMIENTO ALMACENADO PARA DAR DE BAJA UNA FACTURA 
 CREATE PROC BAJAFACTURA
@ID INT
AS
    
	IF EXISTS (SELECT ID_FACTURA FROM FACTURA WHERE ID_FACTURA=@ID)
  BEGIN
       UPDATE FACTURA SET ESTADO=0 where ID_FACTURA=@ID
  END

GO

--FILTRO DE BUSQUEDA
CREATE PROC BUSQUEDAFAC
AS
SELECT * FROM FACTURA
GO

create proc cargaCombo
as 
select DISTINCT ID_PRODUCTO,NOMBRE_PRODUCTO from PRODUCTOS
go

create proc cargaComboUsuarios
as 
select DISTINCT ID_USUARIO,PRIMER_NOMBRE from USUARIOS
go

create PROC BUSQUEDAPRODUCTO
@ID INT
AS
SELECT * FROM PRODUCTOS WHERE ID_PRODUCTO = @ID
GO
------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------VENTAS-------------------------------------------------------------------------------------------------------
--CREACION TABLA VENTAS
CREATE TABLE VENTAS(
ID_VENTAS INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
CANTIDAD_VENDIDA INT NOT NULL,
USUARIO VARCHAR (20) NOT NULL,
CLIENTE VARCHAR (20) NOT NULL,
FECHA DATETIME NOT NULL,
TOTAL FLOAT NOT NULL,
ID_FACTUTRA INT FOREIGN KEY REFERENCES FACTURA(ID_FACTURA)NOT NULL,
ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTOS(ID_PRODUCTO) NOT NULL
)
GO

-- INGRESAR INVENTA
create PROC INSERTARVENTA
@CANTIDAD_VENIDA INT,
@USUARIO VARCHAR(20),
@CLIENTE VARCHAR(20),
@FECHA DATETIME,
@TOTAL FLOAT 
AS
declare @idfac int
declare @idpro int
set @idfac=(select top 1 ID_FACTURA from FACTURA order by ID_FACTURA desc)
set @idpro=(select top 1 ID_PRODUCTO from FACTURA order by ID_PRODUCTO desc)
INSERT INTO VENTAS(CANTIDAD_VENDIDA, USUARIO,CLIENTE, FECHA, TOTAL,ID_FACTUTRA,ID_PRODUCTO) VALUES (@CANTIDAD_VENIDA,@USUARIO, @CLIENTE, @FECHA, @TOTAL,@idfac,@idpro)
GO

create PROC MOSTRARFACTURA
AS
SELECT ventas.USUARIO as'Cajero',CLIENTE as 'Nombre cliente',COD_PRODUCTO as 'Codigo de producto', CANTIDAD_VENDIDA as'Cantidad vendida',
PRECIO_VENTA as'Precio producto',
VENTAS.TOTAL as 'Subtotal',FACTURA.TOTAL as 'Total',FACTURA.FECHA as'Fecha'
 FROM FACTURA inner join VENTAS on FACTURA.ID_FACTURA=VENTAS.ID_FACTUTRA inner join PRODUCTOS on VENTAS.ID_PRODUCTO=PRODUCTOS.ID_PRODUCTO
GO

------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------DETALLE DE VENTAS-----------------------------------------------------------------------------------------------


CREATE TABLE DETALLEVENTA
(
ID_VENTAS INT FOREIGN KEY  REFERENCES  VENTAS(ID_VENTAS) NOT NULL,
ID_PRODUCTO  INT FOREIGN KEY REFERENCES PRODUCTOS(ID_PRODUCTO) NOT NULL,
PRECIO  FLOAT ,
CANTIDAD INT
)
GO

------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------TABLA SERVICIOS-------------------------------------------------------------------------------------------------
--CREACION TABLA SERVCIOS
CREATE TABLE SERVICIOS
(
ID_SERVICIOS INT  IDENTITY (1,1)PRIMARY KEY NOT NULL,
SERVICIOS VARCHAR(20) NOT NULL,
DESCRIPCION VARCHAR(MAX) NOT NULL,
COSTO FLOAT NOT NULL,
CATEGORIA VARCHAR (20) NOT NULL
)
GO


create table documentos(
idDocumento int identity(1,1) primary key,
realnombre varchar(50),
documento varbinary(max)
)
go

create PROC MOSTRARDOCUMENTOS
AS
SELECT idDocumento as Numero,realnombre as 'Archivo guardado' FROM documentos 
GO


create PROC AGREGARDOCUMENTO
@NOMBRE VARCHAR(MAX),
@documento varbinary(Max)
AS
declare @idcl as char(10)
set @idcl=(select documento from documentos where documento=@documento)
if(@documento=@idcl)
  begin
    print 'Documento ya guardado'
  end
  else
  begin
	INSERT INTO documentos(realnombre,documento) VALUES (@NOMBRE, @documento)
 end
GO

create PROC BUSQUEDADOCUMENTO
@ID INT
AS
SELECT idDocumento as Numero,realnombre as 'Archivo guardado' FROM documentos WHERE idDocumento = @ID
GO





